### ISSUE TITLE
Things to be fixed part 2

### ISSUE THREAD

**Issue by JorunnaParva06** [Slug-Studios/Imposter-Syndrome#3]
-Quandale Dingle C gets stuck sometimes
-When Quandale Dingle C jumpscares the player the camera is inside his neck
-Shrek, Imposter and Walter are still very loud, can be heard from very far away making avoiding Shrek and Imposter not too hard, so I think another decently sized volume decrease would be good
-Maybe change the win screen to the 3D render I made? that would be pretty cool like it took hours to render pleasekjkiwefkjfsjfkhjs dkhfjd hmjhdjdsjf

**Comment by Dangerdino30** [comment]
All issues have been dealt with
