### ISSUE TITLE
Things to be fixed #3

### ISSUE THREAD

**Issue by JorunnaParva06** [Slug-Studios/Imposter-Syndrome#4]
-Quandale Dingle A jumpscare doesn't play animation when jumpscared, idk if other entities have this issue too as I couldn't find them so just take a look at that
-I did notice entities are a bit hard to come by, however I believe that is probably fine.
-That's about it for now, take a look at how jumpscares work and have a good day

**Comment by Dangerdino30** [comment]
Fixed Jumpscares
